# This workflow creates all environment-specific resources that are shared across applications.
# This needs to run before creating an application-specific environment.
name: 02 - Manually create a shared environment

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create.'
        options:
          - dev
          - staging
          - prod
        required: true
        default: 'dev'
jobs:
  deploy-network-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    name: Deploy the network stack
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: deployment
        run: npm install

      - name: Deploy network stack
        env:
          ENVIRONMENT_NAME: ${{ github.event.inputs.environmentName }}
        working-directory: deployment
        run: npm run network:deploy
