name: 05 - Deploy the application

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_APPLICATION_NAME: ${{ vars.AWS_APPLICATION_NAME }}

on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: "The Docker image to deploy"
        required: true
      environmentName:
        description: 'The name of the environment to create.'
        options:
          - dev
          - staging
          - prod
        required: true
        default: 'dev'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy Todo App
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Setup environment
        run: |
          echo "APP_ENVIRONMENT_NAME=${{ github.event.inputs.environmentName }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=${{ github.event.inputs.docker-image-tag }}" >> $GITHUB_ENV

      - name: Deploy
        working-directory: cdk
        run: npm run service:deploy
